### ISSUE TITLE
No external dependencies

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/golang-ex#10]
I propose this example to be a simple app based on net/http without any external dependencies.

If earlier I already doubted why we use a framework, and why beego in particular; now I have a reason to dislike using beego: https://github.com/openshift/golang-ex/pull/9#issuecomment-173227490.

Beego has recently merged PRs that break the public API and even break their own [examples](https://github.com/beego/samples):
https://github.com/astaxie/beego/pull/1540
https://github.com/astaxie/beego/pull/1567

There's no clear "winner" in the land of Go Web Frameworks, and many apps, including OpenShift rely on net/http without a web framework.

@bparees @mfojtik @mnagy @php-coder @PI-Victor thoughts?

**Comment by bparees** [comment]
i have no particular objections.  the golang example is more about having a static/binary example than what framework it supports.

**Comment by PI-Victor** [comment]
:+1: i remember we discussed about it and i couldn't agree more

**Comment by rhcarvalho** [comment]
Fixed by https://github.com/openshift/golang-ex/pull/9
