### ISSUE TITLE
Consider relicensing under Apache or using SQLite's Public Domain License

### ISSUE THREAD

**Issue by jawnsy** [openshift/golang-ex#14]
Hi,

If possible (e.g. if Red Hat owns the copyright for this code, or if all authors/copyright owners can agree to such a change), I recommend relicensing this code under the Apache Software License, which would be compatible with OpenShift Origin's licensing terms and covers software patent grants.

If you prefer an even more permissive license (I can't blame you - I use Public Domain for some of my own software), then I would suggest using SQLite's Public Domain terms [0]:

> The author or authors of this code dedicate any and all copyright interest in this code to the public domain. We make this dedication for the benefit of the public at large and to the detriment of our heirs and successors. We intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this code under copyright law. 

This is because CC0  is not intended to be a software license; see [1, 2].

Jonathan

[0] https://www.sqlite.org/copyright.html
[1] https://blog.creativecommons.org/2011/04/15/using-cc0-for-public-domain-software/
[2] https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

**Comment by richardfontana** [comment]
@jawnsy Likely historical explanation for the use of CC0 here: not too long after the launch of OpenShift Origin (or maybe even before?) I recommended use of CC0 for sample code and things like that. The idea was that we should explicitly place sample code under legal terms that grant as much permission as possible, so no one using or adapting the code would have to worry about complying with any conditions. At the time (~4 years ago) I was somewhat enthusiastic about CC0 in general and particularly for purposes like this, even though CC0 was not originally designed for software. 

I am less enthusiastic about CC0 today. The explicit denial of a grant of patent rights in CC0 is at least politically problematic and I think CC0 is excessively complex for what it is trying to do). I woudn't recommend the sqlite approach, but I sort of like the [Unlicense](https://choosealicense.com/licenses/unlicense/) as well as the Zero Clause BSD license, also known as the [Free Public License 1.0.0.](https://opensource.org/licenses/FPL-1.0.0)

**Comment by jawnsy** [comment]
@richardfontana Thanks for sharing that bit of institutional memory :smile: I'm glad that it was done on the recommendation of an attorney and will certainly defer to you here :+1:

Are the MIT or BSD licenses insufficiently permissive for example code?  Or Apache 2.0, which would be compatible with origin?  I ask because these seem like more common licenses, and thus would be more palatable to lawyers at older Fortune 50-type companies (understandably so - it can be risky to be too innovative when it comes to finance or law).  These licenses all seemed pretty "do whatever you want" to me, so I'm not sure what the Zero Clause BSD License gives in addition?

The Free Public License and Zero Clause BSD License don't seem to have been evaluated by Debian against their [Free Software Guidelines](https://wiki.debian.org/DFSGLicenses) and speaking from past experience it's typically easiest when the license is on that list for inclusion into Debian (and thus also Ubuntu). [Fedora is okay with Unlicense](https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#Software_License_List), but I can't find the Zero Clause BSD License/Free Public License

Thanks for the clarification, though since it's not specific to this project, it might be worthy of public guidance on the Red Hat site?
