### ISSUE TITLE
Root access and build strategy

### ISSUE THREAD

**Issue by scriptdealer** [openshift/golang-ex#17]
I'm getting this result for 'oc new-app':
- The image does not expose any ports - if you want to load balance or send traffic to this component    you will need to create a service with 'expose dc/<app> --port=[port]' later
- WARNING: Image "<app>" runs as the 'root' user which may not be permitted by your cluster administrator
- error: buildconfigs "<app>" is forbidden: build strategy Docker is not allowed

So when I run 'oc get services' I've got none.

**Comment by rjstone** [comment]
This is related to https://bugzilla.redhat.com/show_bug.cgi?id=1355596

Build strategy Docker is disallowed so this example won't work as is.

**Comment by Fale** [comment]
This seems to be fixed in version 1.5/3.5, so I guess this can be closed

**Comment by ValentinFunk** [comment]
Is it going to be allowed at some point? How would you go about building a docker image?
