### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by chmouel** [openshift/golang-ex#3]
trying it the steps as mentionned in the README and i am getting : 

<pre>
$ oc build-logs beego-example-1 -f                                                                                                   [master]
I1021 04:34:02.514436       1 sti.go:74] The value of ALLOWED_UIDS is [1-]
I1021 04:34:02.519865       1 docker.go:228] Pulling image docker.io/library/golang:1.4.2-onbuild
I1021 04:34:48.017951       1 sti.go:96] Creating a new S2I builder with build config: "Builder Image:\t\tdocker.io/library/golang:1.4.2-onbuild\nSource:\t\t\thttps://github.com/chmouel/golang-ex\nOutput Image Tag:\t172.30.132.87:5000/chmouelb/beego-example:latest\nEnvironment:\t\tOPENSHIFT_BUILD_NAMESPACE=chmouelb,OPENSHIFT_BUILD_SOURCE=https://github.com/chmouel/golang-ex,OPENSHIFT_BUILD_NAME=beego-example-1\nIncremental Build:\tdisabled\nRemove Old Build:\tdisabled\nForce Pull:\t\tdisabled\nQuiet:\t\t\tdisabled\nLayered Build:\t\tdisabled\nDocker Endpoint:\tunix:///var/run/docker.sock\n"
I1021 04:34:48.027589       1 docker.go:211] Image docker.io/library/golang:1.4.2-onbuild available locally
F1021 04:34:48.061875       1 builder.go:54] Build error: image "docker.io/library/golang:1.4.2-onbuild" must specify a user that is numeric and within the range of allowed users
</pre>

**Comment by thincal** [comment]
I just try this example, and meet same error.

@bparees does that mean the standard docker image can't be used any more ? Is there a way to fix it but still leveraging the existed image such as this `golang:1.4.2-onbuild` ?

**Comment by bparees** [comment]
Please see this doc:  https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-specific-guidelines

Specifically the section about supporting arbitrary user ids discusses how to utilize an image that attempts to run with a specific user ID (as the golang image does). 

Closing this issue as I think that doc should explain the error you're getting and the solution, but please reopen with more feedback if it does not.

**Comment by rhcarvalho** [comment]
Hit this myself too... IMHO just following the docs is not enough, and this example won't work for users :(
Fortunately, I have a fix to make this example work out-of-the-box: #6

**Comment by aperrot42** [comment]
Ouch I followed the s2i image creation tutorial from OpenShift and got that on the face when trying to deploy to oc ... maybe some consolidation to do on s2i images creation instructions.
